'use client';
import Link from 'next/link';
import {actOnConversation} from './actions';
import {useEffect,useRef,useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import {ArrowDown,ArrowLeft,ArrowRight,Bot,CheckCheck,ChevronDown,ExternalLink,Globe,Inbox,Info,Camera,LoaderCircle,MessageCircle,Package,RefreshCw,Search,ShieldCheck,UserRound,X,AlertCircle,Send} from 'lucide-react';
export type Message={id:string,source:string,status:string,timestamp:number,text:string,attachments:{url:string}[]};
export type Conversation={id:string,channel:string,paused:boolean,reason:string|null,name:string|null,preview:string,needsSupport:boolean};
export type Detail=Conversation&{history:Message[],context:{role:string,content:string,timestamp?:number}[],orders:{number:string}[],support:{id:string,status:string,reason:string}[],nextOffset:number|null};
type Props={list:{items:Conversation[],nextOffset:number|null}|null,detail:Detail|null,error:boolean,selected:string,channel:string,listOffset:number,messageOffset:number};
const channels=[['','Svi'],['facebook','Facebook'],['instagram','Instagram'],['web','Sajt']];
const label=(c:string)=>c==='web'?'Sajt':c==='instagram'?'Instagram':'Facebook';
const names:Record<string,string>={sent:'Poslato',done:'Obrađeno',pending:'Na čekanju',failed:'Neuspešno',skipped:'Preskočeno',suppressed:'Nije poslato',uncertain:'Ishod slanja nije potvrđen',sending:'Slanje u toku',recorded:'Zabeleženo bez novog mejla',superseded:'Rešeno / zamenjeno'};
const date=(t:number)=>new Date(t).toLocaleDateString('sr-Latn-RS',{timeZone:'Europe/Belgrade',day:'numeric',month:'long',year:'numeric'});
const time=(t:number)=>new Date(t).toLocaleTimeString('sr-Latn-RS',{timeZone:'Europe/Belgrade',hour:'2-digit',minute:'2-digit'});
const name=(c:Conversation)=>c.name||label(c.channel)+' kupac '+c.id.split(':').at(-1)?.slice(-8);
function Avatar({title,channel}:{title:string,channel:string}){return <span aria-hidden="true" className={'flex size-10 shrink-0 items-center justify-center rounded-2xl text-sm font-semibold '+(channel==='instagram'?'bg-fuchsia-100 text-fuchsia-700':channel==='web'?'bg-teal-100 text-teal-700':'bg-blue-100 text-blue-700')}>{title.split(' ').slice(0,2).map(s=>s[0]).join('').toUpperCase()}</span>}
function ChannelIcon({channel}:{channel:string}){const Icon=channel==='web'?Globe:channel==='instagram'?Camera:MessageCircle;return <Icon size={13} aria-hidden="true"/>}
function Attachment({url}:{url:string}){const [failed,setFailed]=useState(false);return <a href={url} target="_blank" rel="noopener noreferrer" className="mt-2 block overflow-hidden rounded-xl border border-black/10 bg-white text-slate-700" aria-label="Otvori sliku ili prilog u novom tabu">{!failed&&<img src={url} alt="Prilog u razgovoru" loading="lazy" referrerPolicy="no-referrer" onError={()=>setFailed(true)} className="h-56 w-full max-w-72 object-contain"/>}<span className="flex items-center justify-between gap-6 px-3 py-2 text-xs">Otvori prilog <ExternalLink size={12}/></span></a>}
export function ConversationWorkspace(props:Props){
 return <ConversationSession key={props.detail?.id??'empty'} {...props}/>;
}
function ConversationSession({list,detail,error,selected,channel,listOffset,messageOffset}:Props){
 const router=useRouter(),[refreshing,startRefresh]=useTransition(),[query,setQuery]=useState(''),[details,setDetails]=useState(false),[scrollState,setScrollState]=useState({offset:messageOffset,atBottom:messageOffset===0});
 const atBottom=scrollState.offset===messageOffset?scrollState.atBottom:messageOffset===0;
 const feed=useRef<HTMLDivElement>(null);
 const [draft,setDraft]=useState(''),[acting,setActing]=useState(false),[notice,setNotice]=useState<{ok:boolean,message:string}|null>(null);
 const mounted=useRef(false);
 useEffect(()=>{mounted.current=true;return ()=>{mounted.current=false;};},[]);
 const [retryPending,setRetryPending]=useState(false);
 const attempt=useRef<{id:string,text:string,requestId:string}|null>(null),busy=useRef(false);
 async function operate(action:'pause'|'resume'|'reply'){
  if(!detail||busy.current)return;busy.current=true;setActing(true);setNotice(null);
  const id=detail.id;
  try{
   let payload:{id:string,action:'pause'|'resume'|'reply',text?:string,requestId?:string}={id,action};
   if(action==='reply'){
    const text=attempt.current?.id===id?attempt.current.text:draft.trim();
    if(!text)return;
    if(!attempt.current||attempt.current.id!==id)attempt.current={id,text,requestId:crypto.randomUUID()};
    payload={...payload,...attempt.current};
   }
   const result=await actOnConversation(payload);if(!mounted.current)return;setNotice(result);
   if(!result.ok&&!result.retrySame)attempt.current=null;
   setRetryPending(!!attempt.current);
   if(result.ok&&action==='reply'){setDraft('');attempt.current=null;setRetryPending(false);}
   startRefresh(()=>router.refresh());
  }catch{if(!mounted.current)return;setRetryPending(!!attempt.current);setNotice({ok:false,message:'Ishod nije potvrđen. Osvežite prepisku; ponovni klik koristi isti pokušaj slanja.'});}
  finally{busy.current=false;if(mounted.current)setActing(false);}
 }
 useEffect(()=>{if(!detail?.paused)return;const timer=setInterval(()=>{if(!busy.current&&document.visibilityState==='visible')startRefresh(()=>router.refresh());},10000);return ()=>clearInterval(timer);},[detail?.id,detail?.paused,router]);
 useEffect(()=>{if(atBottom&&messageOffset===0&&feed.current)feed.current.scrollTop=feed.current.scrollHeight;},[detail?.history.length,atBottom,messageOffset]);
 const href=(extra:Record<string,string|number>)=>'/admin/razgovori?'+new URLSearchParams({...(channel?{channel}:{}),offset:String(listOffset),...(selected?{conversation:selected}:{}),...Object.fromEntries(Object.entries(extra).map(([k,v])=>[k,String(v)]))}).toString();
 const back='/admin/razgovori?'+new URLSearchParams({...(channel?{channel}:{}),offset:String(listOffset)}).toString();
 useEffect(()=>{if(feed.current)feed.current.scrollTop=messageOffset===0?feed.current.scrollHeight:0;},[detail?.id,messageOffset]);
 const normalize=(s:string)=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'dj');
 const items=(list?.items??[]).filter(c=>normalize(name(c)+' '+c.preview).includes(normalize(query)));
 return <div className="bg-slate-50/70 p-3 md:p-6">
 {error&&<div role="alert" className="mb-4 flex items-center gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><AlertCircle size={18}/>Razgovori trenutno nisu dostupni. Pokušajte da osvežite prikaz.</div>}
 <div className="flex h-[calc(100dvh-215px)] min-h-[520px] overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-[0_8px_40px_-20px_rgba(15,23,42,0.2)] lg:min-h-[580px]">
 <aside aria-label="Lista razgovora" className={(detail?'hidden lg:flex ':'flex ')+'w-full shrink-0 flex-col border-r border-slate-200 lg:w-80 xl:w-96'}>
  <div className="p-5 pb-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Inbox size={19} className="text-blue-600"/><h2 className="font-semibold text-slate-900">Inbox</h2></div><button type="button" disabled={refreshing} onClick={()=>startRefresh(()=>router.refresh())} aria-label="Osveži razgovore" className="rounded-xl p-2 text-slate-500 transition hover:bg-slate-100 disabled:opacity-50">{refreshing?<LoaderCircle size={17} className="animate-spin"/>:<RefreshCw size={17}/>}</button></div>
  <div className="relative mt-4"><Search size={16} className="pointer-events-none absolute left-3 top-3 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Pretraži prikazane razgovore" placeholder="Pretraži ovu stranu…" className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 pl-9 pr-9 text-sm outline-none transition focus:border-blue-400 focus:ring-2 focus:ring-blue-100"/>{query&&<button type="button" aria-label="Očisti pretragu" onClick={()=>setQuery('')} className="absolute right-2 top-2.5 text-slate-400"><X size={16}/></button>}</div>
  <nav aria-label="Kanali" className="mt-3 flex gap-1 rounded-xl bg-slate-100 p-1">{channels.map(([value,title])=><Link key={value} prefetch={false} href={'/admin/razgovori?'+new URLSearchParams(value?{channel:value}:{}).toString()} aria-current={channel===value?'page':undefined} className={'flex-1 rounded-lg px-2 py-2 text-center text-xs font-medium transition '+(channel===value?'bg-white text-blue-700 shadow-sm':'text-slate-500 hover:text-slate-900')}>{title}</Link>)}</nav></div>
  <div className="flex items-center justify-between px-5 pb-3 text-[11px] font-medium uppercase tracking-wider text-slate-400"><span>Razgovori</span><span>{list?.items.length?listOffset+1+'–'+(listOffset+list.items.length):'0'}</span></div>
  <ul className="min-h-0 flex-1 space-y-1 overflow-y-auto px-2 pb-2">{items.map(c=><li key={c.id}><Link prefetch={false} href={href({conversation:c.id,historyOffset:0})} aria-current={selected===c.id?'page':undefined} className={'group flex gap-3 rounded-2xl border p-3 transition '+(selected===c.id?'border-blue-100 bg-blue-50':'border-transparent hover:bg-slate-50')}><Avatar title={name(c)} channel={c.channel}/><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><strong className="truncate text-sm font-semibold text-slate-900">{name(c)}</strong>{c.needsSupport&&<span title="Razgovor ima zahtev podršci" className="size-2 shrink-0 rounded-full bg-amber-400"/>}</div><p className="mt-1 line-clamp-2 break-words text-xs leading-5 text-slate-500">{c.preview||'Otvori prepisku'}</p><span className="mt-2 flex items-center gap-1.5 text-[10px] text-slate-400"><ChannelIcon channel={c.channel}/>{label(c.channel)}<span className={'ml-auto '+(c.paused?'text-amber-600':'text-emerald-600')}>{c.paused?'Bot pauziran':'Bot aktivan'}</span></span></div></Link></li>)}</ul>
  {!items.length&&<p className="px-5 py-8 text-center text-sm text-slate-500">{query?'Nema rezultata na ovoj strani.':'Nema razgovora za ovaj kanal.'}</p>}
  <div className="flex items-center justify-between border-t border-slate-100 px-4 py-3 text-xs text-slate-500">{listOffset>0?<Link prefetch={false} className="flex items-center gap-1 rounded-lg px-2 py-1.5 hover:bg-slate-100" href={href({offset:Math.max(0,listOffset-50)})}><ArrowLeft size={14}/>Prethodni</Link>:<span>Najnoviji razgovori</span>}{list?.nextOffset!=null&&<Link prefetch={false} className="flex items-center gap-1 rounded-lg px-2 py-1.5 hover:bg-slate-100" href={href({offset:list.nextOffset})}>Sledeći<ArrowRight size={14}/></Link>}</div>
 </aside>
 <section aria-label="Prepiska" className="relative flex min-w-0 flex-1 flex-col">
 {detail?<>
  <div className="flex items-center gap-3 border-b border-slate-100 bg-white px-4 py-4 md:px-6"><Link href={back} aria-label="Nazad na razgovore" className="rounded-xl p-2 text-slate-500 lg:hidden"><ArrowLeft size={18}/></Link><Avatar title={name(detail)} channel={detail.channel}/><div className="min-w-0 flex-1"><h2 className="truncate text-sm font-semibold text-slate-900 md:text-base">{name(detail)}</h2><p className="mt-1 flex items-center gap-2 text-xs text-slate-500"><ChannelIcon channel={detail.channel}/>{label(detail.channel)}<span className={'size-1.5 rounded-full '+(detail.paused?'bg-amber-400':'bg-emerald-500')}/>{detail.paused?'Bot pauziran':'Bot aktivan'}</p></div><button type="button" aria-label="Detalji razgovora" aria-expanded={details} onClick={()=>setDetails(!details)} className={'flex items-center gap-2 rounded-xl px-3 py-2 text-xs font-medium transition '+(details?'bg-blue-50 text-blue-700':'bg-slate-50 text-slate-600 hover:bg-slate-100')}><Info size={16}/><span className="hidden sm:inline">Detalji</span>{detail.support.length>0&&<span className="rounded-md bg-amber-100 px-1.5 py-0.5 text-amber-800">{detail.support.length}</span>}</button><button type="button" disabled={refreshing} aria-label="Osveži prepisku" onClick={()=>startRefresh(()=>router.refresh())} className="rounded-xl p-2 text-slate-400 hover:bg-slate-50">{refreshing?<LoaderCircle size={17} className="animate-spin"/>:<RefreshCw size={17}/>}</button></div>
  <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-100 px-4 py-2 md:px-6"><p className="text-xs text-slate-500">{detail.paused?'Vi vodite razgovor. Bot ne odgovara.':'Preuzmite razgovor da odgovorite kupcu.'}</p><button type="button" disabled={acting||refreshing} onClick={()=>operate(detail.paused?'resume':'pause')} className="rounded-xl bg-blue-50 px-4 py-2 text-xs font-semibold text-blue-700 transition hover:bg-blue-100 disabled:opacity-50">{acting?'Obrađujem…':detail.paused?'Vrati botu':'Preuzmi razgovor'}</button></div>
  {details&&<div className="max-h-64 shrink-0 space-y-3 overflow-y-auto border-b border-slate-200 bg-slate-50 px-5 py-4 text-sm">{detail.paused&&<p className="text-amber-800">Razlog pauze: {detail.reason||'Ručno pauzirano'}</p>}{detail.orders.length>0&&<div className="flex flex-wrap items-center gap-2"><Package size={16} className="text-slate-400"/>{detail.orders.map(o=><span key={o.number} className="rounded-lg border border-slate-200 bg-white px-2 py-1 text-xs font-medium">{o.number}</span>)}</div>}{detail.support.length>0&&<details><summary className="cursor-pointer font-medium">Zahtevi korisničkoj podršci ({detail.support.length})</summary><div className="mt-2 space-y-2">{detail.support.map(s=><div key={s.id} className="rounded-xl border border-amber-100 bg-white p-3"><p>{s.reason}</p><p className="mt-1 text-xs text-slate-500">{names[s.status]||s.status}</p></div>)}</div></details>}{detail.context.length>0&&<details><summary className="cursor-pointer font-medium">Uvezene poruke i sačuvani kontekst</summary>{detail.context.map((m,i)=><p className="mt-3 whitespace-pre-wrap break-words text-xs leading-5" key={i}><strong>{m.role==='user'?'Kupac':'SPC iz konteksta'}: </strong>{m.content}</p>)}</details>}<p className="text-xs text-slate-500">Prikazane su poruke koje je SPC servis primio ili uvezao.</p></div>}
  <div ref={feed} onScroll={()=>{const el=feed.current;if(el)setScrollState({offset:messageOffset,atBottom:el.scrollHeight-el.scrollTop-el.clientHeight<80});}} className="min-h-0 flex-1 overflow-y-auto bg-slate-50/70 px-4 py-5 md:px-8">
  {detail.nextOffset!=null&&<div className="mb-6 text-center"><Link prefetch={false} href={href({historyOffset:detail.nextOffset})} className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-2 text-xs font-medium text-slate-600 hover:border-blue-300"><ChevronDown size={14} className="rotate-180"/>Starije poruke</Link></div>}
  {detail.history.map((m,i)=>{const customer=m.source==='Kupac',failed=m.status==='failed',pending=m.status==='pending';return <div key={m.id}>{(i===0||date(m.timestamp)!==date(detail.history[i-1].timestamp))&&<div className="my-6 flex justify-center"><span className="rounded-full border border-slate-200/60 bg-white/80 px-3 py-1 text-[11px] text-slate-400">{date(m.timestamp)}</span></div>}<article className={'mb-4 flex '+(customer?'justify-start':'justify-end')}><div className="max-w-[92%] sm:max-w-[80%] xl:max-w-[68%]"><p className={'mb-1.5 flex items-center gap-1.5 px-1 text-[10px] font-medium text-slate-400 '+(customer?'':'justify-end')}>{customer?<UserRound size={11}/>:m.source==='Bot'?<Bot size={12}/>:<UserRound size={11}/>} {m.source}</p><div className={'rounded-2xl px-4 py-3 text-sm leading-6 shadow-sm '+(customer?'rounded-tl-md border border-slate-200/70 bg-white text-slate-800':m.source==='Bot'?'rounded-tr-md bg-blue-600 text-white':'rounded-tr-md border border-teal-100 bg-teal-50 text-teal-900')}><p className="whitespace-pre-wrap break-words [overflow-wrap:anywhere]">{m.text.split(/(https:\/\/[^\s<>]+)/g).map((part,k)=>part.startsWith('https://')?<a key={k} href={part} target="_blank" rel="noopener noreferrer" className="underline underline-offset-2 hover:opacity-80">{part}</a>:part)}</p>{m.attachments.map((a,j)=><Attachment key={a.url+j} url={a.url}/>)}<p className={'mt-2 flex items-center justify-end gap-1.5 text-[10px] leading-4 '+(failed?(m.source==='Bot'?'text-red-100':'text-red-700'):pending?(m.source==='Bot'?'text-amber-100':'text-amber-700'):!customer&&m.source==='Bot'?'text-blue-100':'text-slate-400')}><span>{time(m.timestamp)}</span>{failed?<><AlertCircle size={11}/>{names[m.status]}</>:pending?<><LoaderCircle size={11}/>{names[m.status]}</>:<><CheckCheck size={12}/><span>{names[m.status]||m.status}</span></>}</p></div></div></article></div>})}
  {!detail.history.length&&<p className="py-12 text-center text-sm text-slate-400">Ovde još nema zabeleženih poruka. Proverite uvezeni kontekst u detaljima.</p>}
  {messageOffset>0&&<div className="mt-5 text-center"><Link prefetch={false} href={href({historyOffset:Math.max(0,messageOffset-100)})} className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-2 text-xs text-slate-600">Novije poruke<ArrowDown size={14}/></Link></div>}
  </div>
  {!atBottom&&messageOffset===0&&<button type="button" aria-label="Idi na najnovije poruke" onClick={()=>feed.current?.scrollTo({top:feed.current.scrollHeight,behavior:'smooth'})} className="absolute bottom-20 right-6 rounded-full border border-slate-200 bg-white p-3 text-blue-600 shadow-lg"><ArrowDown size={18}/></button>}
  <div className="shrink-0 border-t border-slate-100 bg-white p-4">
   {notice&&<p role={notice.ok?'status':'alert'} className={'mb-3 text-xs '+(notice.ok?'text-emerald-700':'text-amber-800')}>{notice.message}</p>}
   <form onSubmit={e=>{e.preventDefault();void operate('reply');}} className="flex items-end gap-2 rounded-2xl border border-slate-200 bg-slate-50 p-2 focus-within:border-blue-400 focus-within:ring-2 focus-within:ring-blue-100">
    <textarea aria-label="Odgovor kupcu" rows={2} maxLength={1800} value={draft} onChange={e=>setDraft(e.target.value)} disabled={!detail.paused||acting||retryPending} placeholder={detail.paused?'Napišite odgovor kupcu…':'Kliknite „Preuzmi razgovor“ da pošaljete odgovor'} className="max-h-36 min-h-14 flex-1 resize-y bg-transparent px-2 py-1 text-sm outline-none disabled:opacity-60"/>
    <button type="submit" disabled={!detail.paused||acting||refreshing||!draft.trim()} aria-label="Pošalji odgovor" className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-blue-600 text-white transition hover:bg-blue-700 disabled:opacity-40">{acting?<LoaderCircle size={18} className="animate-spin"/>:<Send size={18}/>}</button>
   </form><p className="mt-2 text-[10px] text-slate-400">Odgovor šaljete kupcu kao Svet Povoljnih Cena. Bot ostaje pauziran do klika „Vrati botu“.</p>
  </div>
 </>:<div className="flex h-full flex-col items-center justify-center px-8 text-center"><div className="mb-6 flex size-20 items-center justify-center rounded-3xl bg-blue-50 text-blue-600"><MessageCircle size={36} strokeWidth={1.4}/></div><h2 className="text-xl font-semibold tracking-tight text-slate-900">Svaki razgovor na svom mestu</h2><p className="mt-3 max-w-xs text-sm leading-6 text-slate-500">Izaberite kupca i pogledajte prepisku, slike, porudžbine i zahteve podršci.</p><span className="mt-6 flex items-center gap-2 rounded-full border border-slate-200 px-3 py-2 text-xs text-slate-400"><ShieldCheck size={14}/>Pristup samo zaposlenima</span></div>}
 </section></div></div>;
}
