import test from 'node:test';import assert from 'node:assert/strict';import {PGlite} from '@electric-sql/pglite';import {randomBytes} from 'node:crypto';import {Store} from '../src/store.mjs';import {createHttpServer} from '../src/server.mjs';
async function setup(){const db=new PGlite(),store=new Store(undefined,randomBytes(32).toString('hex'));await store.pool.end();store.pool={query:async(sql,args)=>{if(!args&&sql.includes('CREATE TABLE')){await db.exec(sql);return {rows:[]};}const r=await db.query(sql,args);return {...r,rowCount:r.affectedRows??r.rows.length};},end:()=>db.close()};await store.init();const server=await createHttpServer({store,worker:{enabled:true},accounts:[],adminToken:'admin-token',websiteSecret:'integration-token'});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));return {store,base:`http://127.0.0.1:${server.address().port}`,close:async()=>{await new Promise(resolve=>server.close(resolve));await store.close();}};}
test('ERP integration credential reads only dedicated operator routes; no public or integration-token admin write access',async()=>{const s=await setup();try{for(const [path,method,token]of [['/operator/conversations','GET',''],['/admin/conversations','GET','integration-token'],['/admin/action','POST','integration-token'],['/operator/conversation','POST','integration-token']]){const r=await fetch(s.base+path,{method,headers:{authorization:'Bearer '+token}});assert.equal(r.status,401);}const r=await fetch(s.base+'/operator/conversations',{headers:{authorization:'Bearer integration-token'}});assert.equal(r.status,200);assert.deepEqual(await r.json(),{items:[],nextOffset:null});}finally{await s.close();}});
test('lists more than 100 conversations with names and scoped history without exposing ERP access tokens',async()=>{const s=await setup();try{
 const state={customer:{shipping:{firstName:'Test',lastName:'Kupac'}},history:[{role:'user',content:'Zdravo'}],orders:[{number:'SPC-1',accessToken:'PRIVATE'}],pending:{quoteToken:'PRIVATE'}};
 for(let i=0;i<105;i++)await s.store.pool.query('INSERT INTO spc_chat_conversations(id,channel,account,sender,state) VALUES($1,$2,$3,$4,$5)',[`web:spc:test-${i}`,'web','spc',String(i),s.store.encode(state)]);
 const headers={authorization:'Bearer integration-token'};const ids=[];let offset=0;do{const p=await(await fetch(`${s.base}/operator/conversations?offset=${offset}`,{headers})).json();ids.push(...p.items.map(x=>x.id));assert.equal(p.items[0].name,'Test Kupac');assert.ok(!JSON.stringify(p).includes('PRIVATE'));offset=p.nextOffset;}while(offset!==null);assert.equal(new Set(ids).size,105);
 const id=ids[0];await s.store.pool.query('INSERT INTO spc_chat_events(id,conversation,payload,status) VALUES($1,$2,$3,$4)',['event-1',id,s.store.encode({text:'Dogovor',echo:true,accessToken:'PRIVATE',timestamp:1}),'done']);await s.store.pool.query('INSERT INTO spc_chat_outbox(id,conversation,payload,status) VALUES($1,$2,$3,$4)',['reply-1',id,s.store.encode({text:'Pokušaj',quoteToken:'PRIVATE',imageUrl:'https://www.svetpovoljnihcena.rs/product.png'}),'pending']);
 const p=await(await fetch(`${s.base}/operator/conversation?id=${encodeURIComponent(id)}`,{headers})).json();assert.ok(!JSON.stringify(p).includes('PRIVATE'));assert.ok(p.history.some(m=>m.source==='Zaposleni'));assert.ok(p.history.some(m=>m.source==='Bot'&&m.status==='pending'));assert.deepEqual(p.orders,[{number:'SPC-1'}]);assert.equal(p.history.find(m=>m.source==='Bot').attachments[0].url,'https://www.svetpovoljnihcena.rs/product.png');
 const invalid=await fetch(s.base+'/operator/conversations?offset=-1',{headers});assert.equal(invalid.status,400);
 }finally{await s.close();}});




