ALTER TABLE "ProductMedia" ADD COLUMN IF NOT EXISTS "thumbUrl" TEXT;
ALTER TABLE "ProductMedia" ADD COLUMN IF NOT EXISTS "cardUrl" TEXT;
ALTER TABLE "ProductMedia" ADD COLUMN IF NOT EXISTS "pdpUrl" TEXT;
