import assert from 'node:assert/strict';
import sharp from 'sharp';
import {describeImage} from '../src/vision.mjs';
import {answer} from '../src/agent.mjs';
const model=process.env.OPENAI_MODEL??'gpt-5.4-mini';
// Synthetic layout fixture, no customer data or real ERP writes.
const fixture=Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="700" height="900"><rect width="700" height="900" fill="white"/><path d="M150 240 L470 240 L370 130 L210 130 Z" fill="#343434"/><path d="M220 130 L220 75 L355 75 L380 140" fill="none" stroke="#555" stroke-width="24"/><text x="95" y="300" font-size="30">GOLDCORE pegla — 210005</text><rect x="200" y="470" width="170" height="170" fill="#557da0"/><rect x="190" y="640" width="200" height="35" fill="#557da0"/><path d="M210 675 L190 790 M370 675 L390 790" stroke="#222" stroke-width="14"/><text x="130" y="845" font-size="30">URBAN stolica — 330001</text></svg>`);
const image='data:image/png;base64,'+(await sharp(fixture).png().toBuffer()).toString('base64');
const visual=await describeImage({image,model});
assert(visual.readable);assert(visual.objects.some(o=>o.visibleSku==='210005'&&/gore|gorn|vrh/i.test(o.position)));assert(visual.objects.some(o=>o.visibleSku==='330001'));
const products=[{sku:'210005',name:'Pegla GOLDCORE',price:999,available:true,slug:'pegla-goldcore'},{sku:'330001',name:'Stolica URBAN',price:2000,available:true,slug:'stolica-urban'}];
const calls=[];const spc=async input=>{calls.push(input);if(input.action==='search')return {ok:true,items:products.filter(p=>(p.sku+' '+p.name).toLowerCase().includes(input.query.toLowerCase()))};if(input.action==='quote')return {ok:true,input:input.input,quoteToken:'synthetic',totals:{shipping:400,total:1399},expiresAt:Date.now()+900000};throw Error('Unexpected write');};
const now=Date.now();const state={history:[],orders:[],customer:{guestEmail:'test@example.test',shipping:{firstName:'Test',lastName:'Kupac',phone:'0601234567',street:'Test ulica',houseNumber:'12',city:'Kragujevac',postalCode:'34000'},paymentMethod:'POUZECE_GOTOVINA',shippingMethod:'KURIR'},visualContext:{createdAt:now,eventId:'photo',images:[{imageNumber:1,...visual}],failed:0}};
const event={id:'selection',channel:'facebook',conversation:'synthetic',timestamp:now,text:'Ovu skroz gore želim jednu, koristi moje podatke.',attachments:[]};
const imageOnly=await answer({state,event:{...event,id:'photo',text:''},spc,model});
assert.equal(imageOnly.quoteCreated,false);assert(!calls.some(c=>c.action==='quote'));
const first=await answer({state,event,spc,model});assert.equal(first.quoteCreated,false);assert.match(first.text,/GOLDCORE|210005/i);assert(!calls.some(c=>c.action==='quote'));
state.history.push({role:'user',content:event.text,timestamp:now},{role:'assistant',content:first.text,timestamp:now+1});
const second=await answer({state,event:{...event,id:'yes',text:'Da, tu peglu GOLDCORE, jednu.'},spc,model});
assert.equal(second.quoteCreated,true);assert.deepEqual(state.pending.input.lines,[{sku:'210005',qty:1}]);
console.log('Vision collage: top iron identified, catalog candidate shown, purchase prepared only after product confirmation. No real order or email sent.');
